обновлен диплой

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -117,13 +117,16 @@ jobs:
           set -e
           set -x
   
-          # Use an absolute path for the venv directory
-          VENV_DIR="/home/deployer/Poleshko_diploma/venv"
+          # Find pip
+          PIP_PATH=$(find /home/deployer/Poleshko_diploma/venv -name pip -executable)
   
-          # Use full path to pip
-          PIP_PATH="$VENV_DIR/bin/pip"
+          # Check if pip was found
+          if [ -z "$PIP_PATH" ]; then
+            echo "Error: pip not found!"
+            exit 1
+          fi
   
-          echo "Installing project dependencies..."
+          echo "Installing project dependencies using pip: $PIP_PATH"
           "$PIP_PATH" install --upgrade pip
           "$PIP_PATH" install -r requirements.txt
   
